## 3. 과제

In [207]:
import pandas as pd
import numpy as np

In [208]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [209]:
#1.서울버스노선이용자수, 서울버스정류소위치 파일 가져와서 각각 df1, df2에 저장합니다. 만약 한글이 깨질 경우 구글링해서 문제를 해결해보세요!
df1= pd.read_csv('/content/drive/MyDrive/와이빅타_2023-2 교육세션/0706 Numpy-Pandas/과제/서울버스노선이용자수.csv')
df2= pd.read_csv('/content/drive/MyDrive/와이빅타_2023-2 교육세션/0706 Numpy-Pandas/과제/서울버스정류소위치.csv')

<ipython-input-209-426ae580f07d>:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df1= pd.read_csv('/content/drive/MyDrive/와이빅타_2023-2 교육세션/0706 Numpy-Pandas/과제/서울버스노선이용자수.csv')

In [210]:
#2. head()와 tail()을 통해 df1, df2 대략적으로 확인합니다, print말고 display 함수를 써보세요!
display(df1.head())
display(df1.tail())
display(df2.head())
display(df2.tail())

,기준일자,노선명,승차_정류장ARS,승차_정류장명,하차_정류장ARS,하차_정류장명,승차_정류장순번,하차_정류장순번,승객수
0,20230521,17,3689.0,청암자이아파트,3255.0,용산역,1.0,12.0,9
1,20230521,17,3298.0,청암동강변삼성아파트,3122.0,한강대교북단,2.0,14.0,3
2,20230521,17,3298.0,청암동강변삼성아파트,3252.0,신용산.지하차도,2.0,11.0,2
3,20230521,17,3298.0,청암동강변삼성아파트,3255.0,용산역,2.0,12.0,19
4,20230521,17,3298.0,청암동강변삼성아파트,3294.0,서부이촌동입구,2.0,15.0,2

,기준일자,노선명,승차_정류장ARS,승차_정류장명,하차_정류장ARS,하차_정류장명,승차_정류장순번,하차_정류장순번,승객수
430382,20230521,NaN,NaN,경성여객(기점가상),7147.0,중랑초등학교,NaN,14.0,2
430383,20230521,NaN,NaN,경성여객(기점가상),7151.0,상봉2동주민센터,NaN,12.0,1
430384,20230521,NaN,NaN,경성여객(기점가상),7155.0,면목6거리,NaN,10.0,1
430385,20230521,NaN,NaN,경성여객(기점가상),7189.0,용마공원입구,NaN,4.0,1
430386,20230521,NaN,NaN,경성여객(기점가상),7191.0,면일초등학교,NaN,3.0,1

     NODE_ID  ARS_ID           정류소명         X좌표        Y좌표
0  100000001    1001        종로2가사거리  126.987750  37.569765
1  100000002    1002    창경궁.서울대학교병원  126.996566  37.579183
2  100000003    1003      명륜3가.성대입구  126.998340  37.582671
3  100000004    1004       종로2가.삼일교  126.987613  37.568579
4  100000005    1005  혜화동로터리.여운형활동터  127.001744  37.586243

         NODE_ID  ARS_ID         정류소명         X좌표        Y좌표
12565  124000334   25995        우성아파트  127.139338  37.550386
12566  124000333   25996        우성아파트  127.140046  37.550643
12567  124000332   25997         조일약국  127.123596  37.533630
12568  124000331   25998         성내시장  127.125497  37.536155
12569  124000330   25999  천호우체국.로데오거리  127.127337  37.540343

In [211]:
#3.각 데이터프레임의 정보를 확인합니다. (서울버스노선이용자수 데이터(df1)에 결측치가 있는 것을 확인할 수 있습니다)
print(df1.info())
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 430387 entries, 0 to 430386
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   기준일자       430387 non-null  int64
 1   노선명        427603 non-null  object
 2   승차_정류장ARS  429627 non-null  float64
 3   승차_정류장명    430387 non-null  object
 4   하차_정류장ARS  430222 non-null  float64
 5   하차_정류장명    430366 non-null  object
 6   승차_정류장순번   429640 non-null  float64
 7   하차_정류장순번   430225 non-null  float64
 8   승객수        430387 non-null  int64
dtypes: float64(4), int64(2), object(3)
memory usage: 29.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12570 entries, 0 to 12569
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   NODE_ID  12570 non-null  int64
 1   ARS_ID   12570 non-null  int64
 2   정류소명     12570 non-null  object
 3   X좌표      12570 non-null  float64
 4   Y좌표      12570 non-null  float64
dtypes: float64(2), int64(2), object(1)
memory usage: 491.1+ KB
None

In [212]:
#4. df1의 노선명 column 중 결측치가 있는 행만 확인해봅니다.(index가 427603인 행부터 결함이 있다는 것을 확인할 수 있습니다.)
df1[df1['노선명'].isnull()]

,기준일자,노선명,승차_정류장ARS,승차_정류장명,하차_정류장ARS,하차_정류장명,승차_정류장순번,하차_정류장순번,승객수
427603,20230521,NaN,7195.0,용마문화복지센터,1006.0,서대문역사거리,1.0,36.0,1
427604,20230521,NaN,7195.0,용마문화복지센터,1010.0,광화문,1.0,34.0,4
427605,20230521,NaN,7195.0,용마문화복지센터,1012.0,종로1가,1.0,33.0,2
427606,20230521,NaN,7195.0,용마문화복지센터,1014.0,종로2가,1.0,32.0,4
427607,20230521,NaN,7195.0,용마문화복지센터,1016.0,종로3가.탑골공원,1.0,31.0,6
...,...,...,...,...,...,...,...,...,...
430382,20230521,NaN,NaN,경성여객(기점가상),7147.0,중랑초등학교,NaN,14.0,2
430383,20230521,NaN,NaN,경성여객(기점가상),7151.0,상봉2동주민센터,NaN,12.0,1
430384,20230521,NaN,NaN,경성여객(기점가상),7155.0,면목6거리,NaN,10.0,1
430385,20230521,NaN,NaN,경성여객(기점가상),7189.0,용마공원입구,NaN,4.0,1
430386,20230521,NaN,NaN,경성여객(기점가상),7191.0,면일초등학교,NaN,3.0,1

In [213]:
# 개수가 2784개인 것을 보아 노선명에 결측치가 있는 행이 index가 427603~430386인 행이라고 추측할 수 있습니다.
print(df1.isnull().sum())
print('-'*50)
print(430386-427602)

기준일자            0
노선명          2784
승차_정류장ARS     760
승차_정류장명         0
하차_정류장ARS     165
하차_정류장명        21
승차_정류장순번      747
하차_정류장순번      162
승객수             0
dtype: int64
--------------------------------------------------
2784

In [214]:
#5. df1에서 index가 427603인 행부터 삭제해서 새로운 df1을 만듭니다.

df1 = df1.dropna(subset=['노선명'])
df1

,기준일자,노선명,승차_정류장ARS,승차_정류장명,하차_정류장ARS,하차_정류장명,승차_정류장순번,하차_정류장순번,승객수
0,20230521,17,3689.0,청암자이아파트,3255.0,용산역,1.0,12.0,9
1,20230521,17,3298.0,청암동강변삼성아파트,3122.0,한강대교북단,2.0,14.0,3
2,20230521,17,3298.0,청암동강변삼성아파트,3252.0,신용산.지하차도,2.0,11.0,2
3,20230521,17,3298.0,청암동강변삼성아파트,3255.0,용산역,2.0,12.0,19
4,20230521,17,3298.0,청암동강변삼성아파트,3294.0,서부이촌동입구,2.0,15.0,2
...,...,...,...,...,...,...,...,...,...
427598,20230521,중랑02,7526.0,새마을금고,7527.0,공판장,23.0,24.0,1
427599,20230521,중랑02,7526.0,새마을금고,7528.0,진주빌라.바다약국,23.0,25.0,2
427600,20230521,중랑02,7526.0,새마을금고,7529.0,진로아파트앞.종점,23.0,26.0,5
427601,20230521,중랑02,7529.0,진로아파트앞.종점,7149.0,동부시장남문입구,26.0,11.0,2
427602,20230521,중랑02,7529.0,진로아파트앞.종점,7529.0,진로아파트앞.종점,26.0,26.0,1

In [215]:
#아직 하차 정류장ARS와 하차_정류장 순번에 결측치가 있는 것을 확인할 수 있습니다.
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 427603 entries, 0 to 427602
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   기준일자       427603 non-null  int64
 1   노선명        427603 non-null  object
 2   승차_정류장ARS  426854 non-null  float64
 3   승차_정류장명    427603 non-null  object
 4   하차_정류장ARS  427439 non-null  float64
 5   하차_정류장명    427582 non-null  object
 6   승차_정류장순번   426867 non-null  float64
 7   하차_정류장순번   427442 non-null  float64
 8   승객수        427603 non-null  int64
dtypes: float64(4), int64(2), object(3)
memory usage: 32.6+ MB

In [216]:
#6. 이번에는 df1에서 결측치가 있는 행을 모두 제거해 새로운 df1을 만듭니다.

df1 = df1.dropna()
df1

,기준일자,노선명,승차_정류장ARS,승차_정류장명,하차_정류장ARS,하차_정류장명,승차_정류장순번,하차_정류장순번,승객수
0,20230521,17,3689.0,청암자이아파트,3255.0,용산역,1.0,12.0,9
1,20230521,17,3298.0,청암동강변삼성아파트,3122.0,한강대교북단,2.0,14.0,3
2,20230521,17,3298.0,청암동강변삼성아파트,3252.0,신용산.지하차도,2.0,11.0,2
3,20230521,17,3298.0,청암동강변삼성아파트,3255.0,용산역,2.0,12.0,19
4,20230521,17,3298.0,청암동강변삼성아파트,3294.0,서부이촌동입구,2.0,15.0,2
...,...,...,...,...,...,...,...,...,...
427598,20230521,중랑02,7526.0,새마을금고,7527.0,공판장,23.0,24.0,1
427599,20230521,중랑02,7526.0,새마을금고,7528.0,진주빌라.바다약국,23.0,25.0,2
427600,20230521,중랑02,7526.0,새마을금고,7529.0,진로아파트앞.종점,23.0,26.0,5
427601,20230521,중랑02,7529.0,진로아파트앞.종점,7149.0,동부시장남문입구,26.0,11.0,2
427602,20230521,중랑02,7529.0,진로아파트앞.종점,7529.0,진로아파트앞.종점,26.0,26.0,1

In [217]:
# 결측치가 모두 없어진 것을 확인할 수 있습니다
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 426725 entries, 0 to 427602
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   기준일자       426725 non-null  int64
 1   노선명        426725 non-null  object
 2   승차_정류장ARS  426725 non-null  float64
 3   승차_정류장명    426725 non-null  object
 4   하차_정류장ARS  426725 non-null  float64
 5   하차_정류장명    426725 non-null  object
 6   승차_정류장순번   426725 non-null  float64
 7   하차_정류장순번   426725 non-null  float64
 8   승객수        426725 non-null  int64
dtypes: float64(4), int64(2), object(3)
memory usage: 32.6+ MB

In [218]:
#7. df1와 df2를 merge하기 위해 ARS의 data type을 통일할 것입니다. df1의 승차_정류장 ARS와 하차_정류장 ARS의 dtype을 float에서 int로 바꿉니다. (람다식 사용!)

df1['승차_정류장ARS'] = df1['승차_정류장ARS'].apply(lambda x: int(x))
df1['하차_정류장ARS'] = df1['하차_정류장ARS'].apply(lambda x: int(x))

df1.info()

<ipython-input-218-297347adb8f7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['승차_정류장ARS'] = df1['승차_정류장ARS'].apply(lambda x: int(x))
<ipython-input-218-297347adb8f7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['하차_정류장ARS'] = df1['하차_정류장ARS'].apply(lambda x: int(x))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 426725 entries, 0 to 427602
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   기준일자       426725 non-null  int64
 1   노선명        426725 non-null  object
 2   승차_정류장ARS  426725 non-null  int64
 3   승차_정류장명    426725 non-null  object
 4   하차_정류장ARS  426725 non-null  int64
 5   하차_정류장명    426725 non-null  object
 6   승차_정류장순번   426725 non-null  float64
 7   하차_정류장순번   426725 non-null  float64
 8   승객수        426725 non-null  int64
dtypes: float64(2), int64(4), object(3)
memory usage: 32.6+ MB

In [219]:
#8. df2에서 ARS_ID, X좌표, Y좌표 column만 선택해 df2_sample을 만듭니다.

df2_sample = df2[['ARS_ID', 'X좌표', 'Y좌표']]
df2_sample

       ARS_ID         X좌표        Y좌표
0        1001  126.987750  37.569765
1        1002  126.996566  37.579183
2        1003  126.998340  37.582671
3        1004  126.987613  37.568579
4        1005  127.001744  37.586243
...       ...         ...        ...
12565   25995  127.139338  37.550386
12566   25996  127.140046  37.550643
12567   25997  127.123596  37.533630
12568   25998  127.125497  37.536155
12569   25999  127.127337  37.540343

[12570 rows x 3 columns]

In [220]:
df1

,기준일자,노선명,승차_정류장ARS,승차_정류장명,하차_정류장ARS,하차_정류장명,승차_정류장순번,하차_정류장순번,승객수
0,20230521,17,3689,청암자이아파트,3255,용산역,1.0,12.0,9
1,20230521,17,3298,청암동강변삼성아파트,3122,한강대교북단,2.0,14.0,3
2,20230521,17,3298,청암동강변삼성아파트,3252,신용산.지하차도,2.0,11.0,2
3,20230521,17,3298,청암동강변삼성아파트,3255,용산역,2.0,12.0,19
4,20230521,17,3298,청암동강변삼성아파트,3294,서부이촌동입구,2.0,15.0,2
...,...,...,...,...,...,...,...,...,...
427598,20230521,중랑02,7526,새마을금고,7527,공판장,23.0,24.0,1
427599,20230521,중랑02,7526,새마을금고,7528,진주빌라.바다약국,23.0,25.0,2
427600,20230521,중랑02,7526,새마을금고,7529,진로아파트앞.종점,23.0,26.0,5
427601,20230521,중랑02,7529,진로아파트앞.종점,7149,동부시장남문입구,26.0,11.0,2
427602,20230521,중랑02,7529,진로아파트앞.종점,7529,진로아파트앞.종점,26.0,26.0,1

In [221]:
df2_sample

       ARS_ID         X좌표        Y좌표
0        1001  126.987750  37.569765
1        1002  126.996566  37.579183
2        1003  126.998340  37.582671
3        1004  126.987613  37.568579
4        1005  127.001744  37.586243
...       ...         ...        ...
12565   25995  127.139338  37.550386
12566   25996  127.140046  37.550643
12567   25997  127.123596  37.533630
12568   25998  127.125497  37.536155
12569   25999  127.127337  37.540343

[12570 rows x 3 columns]

In [222]:
#9. ARS 번호를 이용하여 df1에 df2_sample을 merge해 '승차_정류장_X좌표', '승차_정류장_Y좌표', '하차_정류장_X좌표', '하차_정류장_Y좌표' 4개의 column을 추가하여 새로운 df1을 만듭니다
# merge할 때 inner 조인 방식을 사용합니다!

df1 = pd.merge(df1, df2_sample, how='inner', left_on='승차_정류장ARS', right_on='ARS_ID')
df1 = df1.rename(columns={'X좌표': '승차_정류장_X좌표', 'Y좌표': '승차_정류장_Y좌표'})

df1 = pd.merge(df1, df2_sample, how='inner', left_on='하차_정류장ARS', right_on='ARS_ID')
df1 = df1.rename(columns={'X좌표': '하차_정류장_X좌표', 'Y좌표': '하차_정류장_Y좌표'})

df1 = df1.drop(columns=['ARS_ID_x', 'ARS_ID_y'])

df1

,기준일자,노선명,승차_정류장ARS,승차_정류장명,하차_정류장ARS,하차_정류장명,승차_정류장순번,하차_정류장순번,승객수,승차_정류장_X좌표,승차_정류장_Y좌표,하차_정류장_X좌표,하차_정류장_Y좌표
0,20230521,17,3689,청암자이아파트,3255,용산역,1.0,12.0,9,126.946555,37.534547,126.965470,37.528749
1,20230521,17,3298,청암동강변삼성아파트,3255,용산역,2.0,12.0,19,126.949318,37.533968,126.965470,37.528749
2,20230521,17,3321,청심경로당,3255,용산역,3.0,12.0,32,126.950560,37.533706,126.965470,37.528749
3,20230521,17,3304,원효2동주민센터,3255,용산역,4.0,12.0,55,126.950950,37.534215,126.965470,37.528749
4,20230521,17,3306,산천동,3255,용산역,5.0,12.0,72,126.954009,37.535339,126.965470,37.528749
...,...,...,...,...,...,...,...,...,...,...,...,...,...
378086,20230521,종로13,1829,부암슈퍼,1846,상명대입구,22.0,25.0,1,126.963860,37.594760,126.957402,37.599854
378087,20230521,종로13,1835,하림각,1874,국민은행.세검정지점,23.0,35.0,1,126.962966,37.597685,126.960786,37.604887
378088,20230521,종로13,1861,상명초등학교,1874,국민은행.세검정지점,28.0,35.0,1,126.956817,37.600905,126.960786,37.604887
378089,20230521,중랑01,7501,중화동종점,7506,수협,1.0,4.0,2,127.082532,37.600060,127.079387,37.599553
378090,20230521,중랑01,7501,중화동종점,7508,태릉시장,1.0,5.0,1,127.082532,37.600060,127.078243,37.599772

In [223]:
#10. 승차정류장의 좌표와 하차정류장의 좌표를 이용해 거리를 구하고 df1에 새로운 column '거리'를 추가해줍니다!
#경도와 위도 1도의 거리는 133.33km라 가정하고 피타고라스의 정리를 사용해 직선거리를 구합니다.

degree_distance = 133.33

lon1 = df1['승차_정류장_X좌표']
lat1 = df1['승차_정류장_Y좌표']
lon2 = df1['하차_정류장_X좌표']
lat2 = df1['하차_정류장_Y좌표']

lon_diff = np.abs(lon2 - lon1)
lat_diff = np.abs(lat2 - lat1)

lon_distance = lon_diff * degree_distance
lat_distance = lat_diff * degree_distance

distance = np.sqrt(lon_distance**2 + lat_distance**2)

df1['거리'] = distance

df1

,기준일자,노선명,승차_정류장ARS,승차_정류장명,하차_정류장ARS,하차_정류장명,승차_정류장순번,하차_정류장순번,승객수,승차_정류장_X좌표,승차_정류장_Y좌표,하차_정류장_X좌표,하차_정류장_Y좌표,거리
0,20230521,17,3689,청암자이아파트,3255,용산역,1.0,12.0,9,126.946555,37.534547,126.965470,37.528749,2.637690
1,20230521,17,3298,청암동강변삼성아파트,3255,용산역,2.0,12.0,19,126.949318,37.533968,126.965470,37.528749,2.263181
2,20230521,17,3321,청심경로당,3255,용산역,3.0,12.0,32,126.950560,37.533706,126.965470,37.528749,2.094877
3,20230521,17,3304,원효2동주민센터,3255,용산역,4.0,12.0,55,126.950950,37.534215,126.965470,37.528749,2.068483
4,20230521,17,3306,산천동,3255,용산역,5.0,12.0,72,126.954009,37.535339,126.965470,37.528749,1.762662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378086,20230521,종로13,1829,부암슈퍼,1846,상명대입구,22.0,25.0,1,126.963860,37.594760,126.957402,37.599854,1.096694
378087,20230521,종로13,1835,하림각,1874,국민은행.세검정지점,23.0,35.0,1,126.962966,37.597685,126.960786,37.604887,1.003359
378088,20230521,종로13,1861,상명초등학교,1874,국민은행.세검정지점,28.0,35.0,1,126.956817,37.600905,126.960786,37.604887,0.749608
378089,20230521,중랑01,7501,중화동종점,7506,수협,1.0,4.0,2,127.082532,37.600060,127.079387,37.599553,0.424657
378090,20230521,중랑01,7501,중화동종점,7508,태릉시장,1.0,5.0,1,127.082532,37.600060,127.078243,37.599772,0.573168

In [224]:
#11. 거리에 따라 내림차순으로 df1을 정렬하고 index를 초기화해줍니다. (제가 실수했는데.. index column도 없애주세요!)

df1 = df1.sort_values(by='거리', ascending=False)
df1 = df1.reset_index(drop=True)
df1

,기준일자,노선명,승차_정류장ARS,승차_정류장명,하차_정류장ARS,하차_정류장명,승차_정류장순번,하차_정류장순번,승객수,승차_정류장_X좌표,승차_정류장_Y좌표,하차_정류장_X좌표,하차_정류장_Y좌표,거리
0,20230521,N26,16285,방화사거리,7550,중랑공영차고지.신내역,4.0,67.0,1,126.810492,37.573086,127.103628,37.613209,39.448192
1,20230521,160,10340,도봉산역광역환승센터,17184,온수역,1.0,58.0,3,127.044352,37.689948,126.823823,37.492827,39.437362
2,20230521,N16,10005,서울북부지방법원.검찰청.도봉역성황당,17184,온수역,4.0,68.0,1,127.044921,37.677775,126.823823,37.492827,38.432878
3,20230521,160,17185,온수역,10006,서울북부지방법원.검찰청.도봉역성황당,60.0,116.0,1,126.824401,37.492777,127.045103,37.677262,38.352746
4,20230521,N16,10009,도봉소방서.방학남부역,17290,온수동종점,7.0,69.0,1,127.042981,37.666333,126.821379,37.491922,37.599779
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378086,20230521,1218,9120,인수동장미원,9120,인수동장미원,8.0,8.0,9,127.015527,37.645033,127.015527,37.645033,0.000000
378087,20230521,144,9120,인수동장미원,9120,인수동장미원,8.0,8.0,6,127.015527,37.645033,127.015527,37.645033,0.000000
378088,20230521,109,9122,가오리역,9122,가오리역,9.0,9.0,1,127.016578,37.641898,127.016578,37.641898,0.000000
378089,20230521,1120,9122,가오리역,9122,가오리역,32.0,32.0,1,127.016578,37.641898,127.016578,37.641898,0.000000
378090,20230521,1139,10168,방학2동주민센터,10168,방학2동주민센터,31.0,31.0,1,127.034622,37.668271,127.034622,37.668271,0.000000

In [225]:
#12. 노선당 몇 개의 경로가 있는지 그리고 각각의 경로 거리의 min, max, mean 값을 나타내봅니다.
route_counts = df1.groupby('노선명').count().reset_index()
print("노선당 경로 개수:")
print(route_counts)

route_stats = df1.groupby('노선명')['거리'].agg(['min', 'max', 'mean']).reset_index()
print("\n노선별 경로 거리 통계:")
print(route_stats)

노선당 경로 개수:
      노선명  기준일자  승차_정류장ARS  승차_정류장명  하차_정류장ARS  하차_정류장명  승차_정류장순번  하차_정류장순번  \
0     150  2175       2175     2175       2175     2175      2175      2175
1     151  1419       1419     1419       1419     1419      1419      1419
2     152  2586       2586     2586       2586     2586      2586      2586
3     160  2625       2625     2625       2625     2625      2625      2625
4     162   981        981      981        981      981       981       981
..    ...   ...        ...      ...        ...      ...       ...       ...
612  종로11   132        132      132        132      132       132       132
613  종로12    81         81       81         81       81        81        81
614  종로13   116        116      116        116      116       116       116
615  중랑01    30         30       30         30       30        30        30
616  중랑02   204        204      204        204      204       204       204

      승객수  승차_정류장_X좌표  승차_정류장_Y좌표  하차_정류장_X좌표  하차_정류장_Y좌표    거리
0    2175        2175        2175        2175        2175  2175
1    1419        1419        1419        1419        1419  1419
2    2586        2586        2586        2586        2586  2586
3    2625        2625        2625        2625        2625  2625
4     981         981         981         981         981   981
..    ...         ...         ...         ...         ...   ...
612   132         132         132         132         132   132
613    81          81          81          81          81    81
614   116         116         116         116         116   116
615    30          30          30          30          30    30
616   204         204         204         204         204   204

[617 rows x 14 columns]

노선별 경로 거리 통계:
      노선명       min        max       mean
0     150  0.000000  37.099725   8.797148
1     151  0.000000  21.733298   5.833723
2     152  0.000000  26.128479   6.862455
3     160  0.000000  39.437362  10.943293
4     162  0.000000  16.976059   5.384766
..    ...       ...        ...        ...
612  종로11  0.000000   4.233186   1.702398
613  종로12  0.000000   2.063608   0.979227
614  종로13  0.160305   2.239106   0.960189
615  중랑01  0.000000   2.021175   1.030255
616  중랑02  0.000000   3.410207   1.524621

[617 rows x 4 columns]

In [226]:
#13. 최종적으로 df1을 csv파일로 만들어줍니다!
#csv 파일에서 한글이 깨지지 않도록 구글링해서 적용해주세요

# 저장하기: .to_csv
df1.to_csv("/content/drive/MyDrive/와이빅타_2023-2 교육세션/0706 Numpy-Pandas/김현호_pandas과제.csv", index=False, encoding='euc-kr') #read_csv와 마찬가지로, 경로 지정 가능

**과제하시느라 수고하셨습니다!!!** <br>
과제는 실습과 과제 때 사용한 현 ipynb 파일과 최종 생성한 csv파일을 제출해주시면 됩니다!,<br>
(ipynb,csv 파일명=> {이름}_pandas과제)